/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accounting;

/**
 *
 * @author dkdks
 */
public class entry extends frame {

    /**
     * Creates new form entry
     */
    public entry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(123, 123, 123));
        setPreferredSize(new java.awt.Dimension(1360, 740));
        setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome");
        add(jLabel2);
        jLabel2.setBounds(660, 50, 210, 14);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(620, 560, 120, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");
        add(jLabel3);
        jLabel3.setBounds(560, 140, 80, 20);

        jLabel4.setForeground(new java.awt.Color(255, 57, 56));
        jLabel4.setText("Username *");
        add(jLabel4);
        jLabel4.setBounds(560, 210, 80, 14);
        add(jTextField2);
        jTextField2.setBounds(560, 230, 243, 20);

        jLabel5.setForeground(new java.awt.Color(255, 57, 56));
        jLabel5.setText("Password *");
        add(jLabel5);
        jLabel5.setBounds(560, 280, 80, 14);
        add(jPasswordField2);
        jPasswordField2.setBounds(560, 300, 243, 20);

        jButton2.setText("SUBMIT");
        add(jButton2);
        jButton2.setBounds(580, 370, 80, 23);

        jButton3.setText("RESET");
        add(jButton3);
        jButton3.setBounds(700, 370, 80, 23);

        jLabel6.setBackground(new java.awt.Color(255, 57, 56));
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setOpaque(true);
        add(jLabel6);
        jLabel6.setBounds(530, 110, 310, 80);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setOpaque(true);
        add(jLabel7);
        jLabel7.setBounds(530, 190, 310, 250);

        jLabel8.setText("jLabel8");
        add(jLabel8);
        jLabel8.setBounds(690, 190, 34, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        global_frame.getContentPane().removeAll();
        global_frame.getContentPane().add(new home());
        global_frame.setVisible(true);
        
        //JPanel setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
